name: JerryZehr
favicon: null
layout_spectrum: 0.54142
typography_spectrum: 0.0725666496437043
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5
  lightness: 0.6562012208160013
  saturation: 0.17521916492842138
  rhythmicContrast: 0.33718148549087346
purpose: []
